Jun 21 15:08:49 - INFO  - [Configuration.java : 512] - Logging configuration successfully loaded from /home/evelyn/linagora/workshop/lsc/lsc-2.1.5/sample/ldap-to-james-user/logback.xml 
Jun 21 15:08:49 - INFO  - [Configuration.java : 532] - LSC configuration successfully loaded from /home/evelyn/linagora/workshop/lsc/lsc-2.1.5/sample/ldap-to-james-user/
Jun 21 15:08:49 - DEBUG - [JamesUserDstService.java : 89] - Task bean is: org.lsc.beans.SimpleBean
Jun 21 15:08:49 - INFO  - [JndiServices.java : 270] - Connecting to LDAP server ldap://localhost:49692/dc=james,dc=org as cn=admin,dc=james,dc=org
Jun 21 15:08:49 - ERROR - [JndiServices.java : 467] - Error opening the LDAP connection to the destination! (javax.naming.CommunicationException: localhost:49692 [Root exception is java.net.ConnectException: Connection refused (Connection refused)])
Jun 21 15:08:49 - ERROR - [Launcher.java : 229] - org.lsc.exception.LscConfigurationException: Configuration exception: javax.naming.CommunicationException: localhost:49692 [Root exception is java.net.ConnectException: Connection refused (Connection refused)]
Jun 21 15:08:49 - DEBUG - [Launcher.java : 230] - org.lsc.exception.LscConfigurationException: Configuration exception: javax.naming.CommunicationException: localhost:49692 [Root exception is java.net.ConnectException: Connection refused (Connection refused)]
org.lsc.exception.LscConfigurationException: Configuration exception: javax.naming.CommunicationException: localhost:49692 [Root exception is java.net.ConnectException: Connection refused (Connection refused)]
	at org.lsc.Task.<init>(Task.java:148) ~[lsc-core-2.1.5.jar:na]
	at org.lsc.SimpleSynchronize.init(SimpleSynchronize.java:104) ~[lsc-core-2.1.5.jar:na]
	at org.lsc.SimpleSynchronize.launch(SimpleSynchronize.java:154) ~[lsc-core-2.1.5.jar:na]
	at org.lsc.Launcher.run(Launcher.java:223) [lsc-core-2.1.5.jar:na]
	at org.lsc.Launcher.launch(Launcher.java:158) [lsc-core-2.1.5.jar:na]
	at org.lsc.Launcher.main(Launcher.java:141) [lsc-core-2.1.5.jar:na]
Caused by: java.lang.RuntimeException: javax.naming.CommunicationException: localhost:49692 [Root exception is java.net.ConnectException: Connection refused (Connection refused)]
	at org.lsc.jndi.JndiServices.getInstance(JndiServices.java:468) ~[lsc-core-2.1.5.jar:na]
	at org.lsc.jndi.AbstractSimpleJndiService.<init>(AbstractSimpleJndiService.java:176) ~[lsc-core-2.1.5.jar:na]
	at org.lsc.jndi.SimpleJndiSrcService.<init>(SimpleJndiSrcService.java:116) ~[lsc-core-2.1.5.jar:na]
	at org.lsc.jndi.PullableJndiSrcService.<init>(PullableJndiSrcService.java:109) ~[lsc-core-2.1.5.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_292]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_292]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_292]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_292]
	at org.lsc.Task.<init>(Task.java:143) ~[lsc-core-2.1.5.jar:na]
	... 5 common frames omitted
Caused by: javax.naming.CommunicationException: localhost:49692
	at com.sun.jndi.ldap.Connection.<init>(Connection.java:243) ~[na:1.8.0_292]
	at com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137) ~[na:1.8.0_292]
	at com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1615) ~[na:1.8.0_292]
	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2849) ~[na:1.8.0_292]
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:347) ~[na:1.8.0_292]
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:225) ~[na:1.8.0_292]
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189) ~[na:1.8.0_292]
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:243) ~[na:1.8.0_292]
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154) ~[na:1.8.0_292]
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84) ~[na:1.8.0_292]
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:695) ~[na:1.8.0_292]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313) ~[na:1.8.0_292]
	at javax.naming.InitialContext.init(InitialContext.java:244) ~[na:1.8.0_292]
	at javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154) ~[na:1.8.0_292]
	at org.lsc.jndi.JndiServices.initConnection(JndiServices.java:211) ~[lsc-core-2.1.5.jar:na]
	at org.lsc.jndi.JndiServices.<init>(JndiServices.java:165) ~[lsc-core-2.1.5.jar:na]
	at org.lsc.jndi.JndiServices.getInstance(JndiServices.java:322) ~[lsc-core-2.1.5.jar:na]
	at org.lsc.jndi.JndiServices.getInstance(JndiServices.java:307) ~[lsc-core-2.1.5.jar:na]
	at org.lsc.jndi.JndiServices.getInstance(JndiServices.java:465) ~[lsc-core-2.1.5.jar:na]
	... 13 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_292]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_292]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_292]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_292]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_292]
	at java.net.Socket.connect(Socket.java:607) ~[na:1.8.0_292]
	at java.net.Socket.connect(Socket.java:556) ~[na:1.8.0_292]
	at java.net.Socket.<init>(Socket.java:452) ~[na:1.8.0_292]
	at java.net.Socket.<init>(Socket.java:229) ~[na:1.8.0_292]
	at com.sun.jndi.ldap.Connection.createSocket(Connection.java:380) ~[na:1.8.0_292]
	at com.sun.jndi.ldap.Connection.<init>(Connection.java:220) ~[na:1.8.0_292]
	... 31 common frames omitted
